// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sesefkntidgstshdprcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlc2Vma250aWRnc3RzaGRwcmNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjYzMDcsImV4cCI6MjA2MTI0MjMwN30.LqCDLQKmbh56hOHBsTqr2fPDVMbtjJ5C2EBchGVe1gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);